### ISSUE TITLE
SyncManager crashes on 1.1.8.

### ISSUE THREAD

**Issue by steventsng** [sendbird/sendbird-syncmanager-ios#11]
When calling `SBSMSyncManager.resumeSynchronize()`, the app crashes with the following error.
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBSMFailedMessageQueue copyWithZone:]: unrecognized selector sent to instance 0x17029a680'`
This happens quite often.

It happens when I call the `SBSMSyncManager.resumeSynchronize()`

**Comment by famous90** [comment]
@steventsng Sorry for your inconvenience. Can you update your SDK to the latest version?

**Comment by steventsng** [comment]
Thanks. I've updated to 1.1.9 a few days ago. I've had a handful of crashes early right after the update, but haven't been able to reproduce it. I'll update if i can get more data on it.
