### ISSUE TITLE
Troubles archiving - bitcode bundle could not be generated

### ISSUE THREAD

**Issue by adamteale** [sendbird/sendbird-syncmanager-ios#3]
Hi guys any help with this?

ld: bitcode bundle could not be generated because 'Pods/SendBirdSyncManager/SendBirdSyncManager.framework/SendBirdSyncManager' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 'Pods/SendBirdSyncManager/SendBirdSyncManager.framework/SendBirdSyncManager' for architecture arm64
18638
    ✗ clang: error: linker command failed with exit code 1 (use -v to see invocation)
18639
    ** ARCHIVE FAILED **
18640
    The following build commands failed:
18641
    	Ld /tmp/sandbox/5c24f5906db86900018dde02/bbbuild/Build/Intermediates.noindex/ArchiveIntermediates/TaskyMVP-QA/InstallationBuildProductsLocation/Applications/myapp.app/myapp  normal arm64
18642
    (1 failure)

**Comment by famous90** [comment]
just resolved bitcode issue. sorry for your inconvenience
